"""eprst

Revision ID: 70387a31a4c8
Revises: eeee92038b28
Create Date: 2022-05-09 22:32:04.529277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70387a31a4c8'
down_revision = 'eeee92038b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microblog posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microblog posts_id'), 'microblog posts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microblog posts_id'), table_name='microblog posts')
    op.drop_table('microblog posts')
    # ### end Alembic commands ###
