"""First

Revision ID: bfa6168a5bff
Revises: 130f3cc89d9f
Create Date: 2022-05-09 22:29:01.015417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfa6168a5bff'
down_revision = '130f3cc89d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microblog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microblog_posts_id'), 'microblog_posts', ['id'], unique=True)
    op.drop_index('ix_microblog posts_id', table_name='microblog posts')
    op.drop_table('microblog posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microblog posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"microblog posts_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tittle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='microblog posts_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='microblog posts_pkey')
    )
    op.create_index('ix_microblog posts_id', 'microblog posts', ['id'], unique=False)
    op.drop_index(op.f('ix_microblog_posts_id'), table_name='microblog_posts')
    op.drop_table('microblog_posts')
    # ### end Alembic commands ###
