"""weird

Revision ID: eeee92038b28
Revises: f60deb2f3cb0
Create Date: 2022-05-09 22:30:25.597323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeee92038b28'
down_revision = 'f60deb2f3cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microblog posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microblog posts_id'), 'microblog posts', ['id'], unique=True)
    op.drop_index('ix_abobus_id', table_name='abobus')
    op.drop_table('abobus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abobus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tittle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='abobus_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='abobus_pkey')
    )
    op.create_index('ix_abobus_id', 'abobus', ['id'], unique=False)
    op.drop_index(op.f('ix_microblog posts_id'), table_name='microblog posts')
    op.drop_table('microblog posts')
    # ### end Alembic commands ###
